const TYPING_TEXTS = {
  uz: [
    "Kosmosda yulduzlar juda ko'p. Oy Yer atrofida aylanadi, Yer esa Quyosh atrofida. Astronavtlar raketada uchib, kosmik stansiyada yashaydilar va yulduzlarni yaqindan o'rganadilar.",
    "Mushuklar juda epchil hayvonlar. Ular tun qorong'isida ham yaxshi ko'radilar. Mo'ylovlari esa masofani o'lchashga yordam beradi. Mushukchalar o'yin o'ynashni yaxshi ko'radilar.",
    "Robotlar odamlarga ko'p ishda yordam beradi. Zavodda ular mashinalar yig'adilar, uyda esa chang yutadilar. Zamonaviy robotlar gapirishni va savollarga javob berishni ham biladilar.",
    "Asalarilar guldan gulga uchib asal yig'adilar. Ular o'z uyasida minglab bo'lib yashaydilar. Har bir asalarining o'z vazifasi bor: kimdir nektar yig'adi, kimdir uyani qo'riqlaydi.",
    "Tog'lar juda baland va go'zal. Ularning cho'qqilarida qor yotadi. Tog'da havo toza, osmon esa juda yaqindek tuyuladi. Alpinistlar cho'qqilarga chiqish uchun uzoq mashq qiladilar.",
    "Suv hayot manbai. Daraxtlar, hayvonlar va odamlar suvsiz yashay olmaydilar. Shuning uchun suvni tejash kerak. Kranni yopiq tutish har birimizning vazifamiz.",
    "Kompyuterlar hozir hamma joyda: maktabda, uyda, do'konda. Ular hisob-kitob qiladilar, rasm chizadilar va musiqa ijro etadilar. Kompyuterga dastur yozadigan odam dasturchi deyiladi.",
    "Do'stlik eng qimmatli boylik. Haqiqiy do'st qiyin paytda yordam beradi va quvonchingni bo'lishadi. Do'stlar bir-biriga halol bo'lishi kerak. Birgalikda har qanday ish osonroq.",
    "Futbol dunyodagi eng ommaviy sport. Maydonda har jamoada o'n bir o'yinchidan bo'ladi. To'pni darvozaga kiritgan jamoa gol uradi. Muxlislar jamoasini qizg'in qo'llab-quvvatlaydilar.",
    "Kitoblar bizni yangi dunyolar bilan tanishtiradi. Ertaklar, sarguzashtlar va ilmiy maqolalar o'qish qiziqarli. Ko'p o'qigan odam ko'p narsani biladi. Kitob o'qish miyani kuchaytiradi.",
    "Qishda qor yog'adi va hamma yoq oppoq bo'ladi. Bolalar qorbobo yasab, qor urishadilar. Ayrim hayvonlar qishda uxlaydilar: ayiq, kirpi va ba'zi qushlar. Bahorda tabiat uyg'onadi.",
    "Dengizda juda ko'p sir bor. Uning chuqurligida g'alati baliqlar yashaydi. Delfinlar aqlli va mehribon hayvonlar hisoblanadi. Okeanlar sayyoramizning katta qismini egallaydi.",
    "Internet orqali dunyoning istalgan nuqtasi bilan bog'lansak bo'ladi. Video qo'ng'iroq, xat va rasmlar bir lahzada yetib boradi. Lekin internetdan ehtiyotkorlik bilan foydalanish muhim.",
    "Bahorda daraxtlar gullaydi, qushlar sayraydi. Dalalar yashil libosga kiradi. Dehqonlar ekin ekadilar va kuzda hosil yig'adilar. Tabiatning har fasli o'ziga yarasha chiroyli.",
    "Musiqa kayfiyatni ko'taradi. Doira, gitara va pianino turli ovozlarga ega. Ba'zi bolalar qo'shiq aytishni, ba'zilari raqsga tushishni yaxshi ko'radilar. Musiqa go'zal san'at.",
    "Chumolilar kichkina, lekin juda kuchli. Ular o'zidan og'ir narsalarni ko'tara oladilar. Chumoli uyasi murakkab shaharchaga o'xshaydi: unda yo'llar, xonalar va omborlar bor.",
    "Samolyotlar osmonda qushlardan ham tez uchadi. Ular qanotlaridagi kuchli dvigatellar yordamida ko'tariladilar. Uchuvchilar samolyotni boshqaradilar va yo'lovchilarni manzilga yetkazadilar.",
    "Sport bilan shug'ullanish sog'liqni mustahkamlaydi. Har kuni ertalab badantarbiya qilish foydali. Yugurish, suzish va sakrash tanani chiniqtiradi. Sog'lom tana — sog'lom fikr asosi.",
    "Yulduzlar tunda osmonni bezaydi. Eng yorug' yulduzlarning o'z nomlari bor. Astronomlar teleskop orqali osmonni kuzatadilar. Somon yo'li galaktikasida milliardlab yulduzlar bor.",
    "Oshqovoq, sabzi va kartoshka foydali sabzavotlar. Ularda vitaminlar ko'p. Meva va sabzavotlarni har kuni iste'mol qilish kerak. Ular tanani kasalliklardan himoya qiladi.",
    "Dasturchilar kompyuter uchun dasturlar yozadilar. Dastur — bu kompyuterga berilgan aniq ko'rsatmalar. Har bir dastur oddiy buyruqlardan boshlanadi. Sen ham kod yozishni o'rganishing mumkin.",
    "Cho'l juda issiq va quruq joy. Unda tuyalar va kaltakesaklar yashaydi. Cho'l o'simliklari suvni tejashni biladilar. Tunda esa cho'l salqin va yulduzli bo'ladi.",
    "Qushlar issiq o'lkalarga kuzda uchib ketadilar. Qaldirg'ochlar, turnalar va laylaklar minglab kilometr yo'l bosadilar. Bahorda ular yana o'z uylariga qaytadilar va in qo'yadilar.",
    "Maktabda biz o'qish, yozish va hisoblashni o'rganamiz. O'qituvchilar bizga bilim beradilar. Sinfdoshlar bilan birga loyihalar qilish qiziqarli. Har bir dars yangi narsa o'rgatadi.",
    "Oilamiz — eng yaqin insonlarimiz. Ota-onamiz bizni parvarish qiladilar, buvamiz ertak aytib beradilar. Oilada bir-biriga yordam berish va hurmat qilish juda muhim.",
    "Yomg'ir bulutlardan tushadi va yerni ho'llaydi. Undan keyin osmonda kamalak paydo bo'lishi mumkin. Kamalakda yetti xil rang bor: qizil, sariq, yashil va boshqalar.",
    "Velosiped ekologik toza transport. U benzin talab qilmaydi va havo ifloslantirmaydi. Velosiped haydash oyoqlarni kuchaytiradi va muvozanatni o'rgatadi. Ko'p shaharlarda veloyo'llar qurilgan.",
    "Dinozavrlar millionlab yillar oldin yashagan. Ayrimlari juda katta, ayrimlari kichkina bo'lgan. Ular haqida biz qazilma suyaklar orqali bilamiz. Olimlar skeletlarni muzeylarda ko'rsatadilar.",
    "Uyqu tanaga dam beradi. Bolalar kechasi to'qqiz-o'n soat uxlashlari kerak. Yaxshi uyqu xotirani mustahkamlaydi va kayfiyatni yaxshilaydi. Uxlashdan oldin telefon o'ynash tavsiya etilmaydi.",
    "Orzular cheksiz bo'ladi. Kimdir shifokor, kimdir uchuvchi, kimdir dasturchi bo'lishni orzu qiladi. Orzuga erishish uchun o'qish va harakat qilish kerak. Katta ish kichik qadamdan boshlanadi."
  ],
  ru: [
    "В космосе очень много звёзд. Луна вращается вокруг Земли, а Земля вокруг Солнца. Космонавты летают на ракетах и живут на космической станции, изучая далёкие планеты.",
    "Кошки очень ловкие животные. Они хорошо видят в темноте, а усы помогают им измерять расстояние. Котята любят играть и быстро растут.",
    "Роботы помогают людям во многих делах. На заводе они собирают машины, а дома пылесосят. Современные роботы умеют разговаривать и отвечать на вопросы.",
    "Пчёлы летают с цветка на цветок и собирают мёд. В улье живут тысячи пчёл, и у каждой своя задача: кто-то собирает нектар, кто-то охраняет дом.",
    "Горы высокие и красивые. На их вершинах лежит снег, а воздух там чистый. Альпинисты долго тренируются, чтобы подняться на самую вершину.",
    "Вода — источник жизни. Деревья, животные и люди не могут без неё. Поэтому воду нужно беречь и не оставлять кран открытым.",
    "Компьютеры сейчас везде: в школе, дома, в магазине. Они считают, рисуют и играют музыку. Человека, который пишет программы, называют программистом.",
    "Дружба — самое дорогое богатство. Настоящий друг поможет в трудную минуту и разделит радость. Друзья должны быть честными друг с другом.",
    "Футбол — самый популярный спорт в мире. В каждой команде на поле одиннадцать игроков. Команда забивает гол, когда мяч попадает в ворота.",
    "Книги знакомят нас с новыми мирами. Читать сказки, приключения и научные статьи очень интересно. Кто много читает, тот много знает.",
    "Зимой идёт снег и всё становится белым. Дети лепят снеговика и играют в снежки. Некоторые животные спят до весны: медведи, ежи и птицы.",
    "В море много тайн. В его глубинах живут удивительные рыбы. Дельфины считаются умными и добрыми, а океаны занимают большую часть планеты.",
    "Через интернет можно связаться с любой точкой мира. Видеозвонки, письма и фотографии доходят за секунды. Но пользоваться интернетом нужно осторожно.",
    "Весной деревья цветут и птицы поют. Поля становятся зелёными. Фермеры сеют семена, а осенью собирают урожай. Каждое время года красиво по-своему.",
    "Музыка поднимает настроение. Барабаны, гитара и пианино звучат по-разному. Одни дети любят петь, другие танцевать. Музыка — прекрасное искусство.",
    "Муравьи маленькие, но очень сильные. Они переносят предметы тяжелее себя. Муравейник похож на сложный город с дорогами, комнатами и складами.",
    "Самолёты летают быстрее птиц. Они поднимаются в небо с помощью мощных двигателей на крыльях. Пилоты ведут самолёт и доставляют пассажиров.",
    "Спорт укрепляет здоровье. Полезно делать зарядку каждое утро. Бег, плавание и прыжки закаляют тело. В здоровом теле — здоровый дух.",
    "Ночью небо украшают звёзды. У самых ярких из них есть свои имена. Астрономы наблюдают за небом в телескопы и открывают новые звёзды.",
    "Тыква, морковь и картофель — полезные овощи. В них много витаминов. Фрукты и овощи нужно есть каждый день, чтобы не болеть.",
    "Программисты пишут программы для компьютеров. Программа — это точные инструкции для машины. Любая программа начинается с простых команд. Ты тоже можешь научиться коду.",
    "Пустыня — жаркое и сухое место. Там живут верблюды и ящерицы. Растения пустыни умеют экономить воду, а ночью там прохладно и звёздно.",
    "Осенью птицы улетают в тёплые края. Ласточки, журавли и аисты преодолевают тысячи километров. Весной они возвращаются домой и строят гнёзда.",
    "В школе мы учимся читать, писать и считать. Учителя дают нам знания. Работать над проектами с одноклассниками интересно, и каждый урок учит новому.",
    "Семья — самые близкие люди. Родители заботятся о нас, бабушка рассказывает сказки. В семье важно помогать друг другу и уважать старших.",
    "Дождь падает из облаков и увлажняет землю. После него на небе может появиться радуга. В радуге семь цветов: красный, жёлтый, зелёный и другие.",
    "Велосипед — экологичный транспорт. Он не требует бензина и не загрязняет воздух. Езда на велосипеде укрепляет ноги и учит равновесию.",
    "Динозавры жили миллионы лет назад. Некоторые были огромными, некоторые совсем маленькими. Мы знаем о них по окаменелостям, которые показывают в музеях.",
    "Сон даёт телу отдых. Детям нужно спать девять-десять часов ночью. Хороший сон укрепляет память и улучшает настроение. Перед сном не играют в телефон.",
    "Мечты безграничны. Кто-то хочет стать врачом, кто-то лётчиком, кто-то программистом. Чтобы мечта сбылась, нужно учиться и действовать. Большое дело начинается с малого шага."
  ],
  en: [
    "Space is full of stars. The Moon travels around the Earth, and the Earth travels around the Sun. Astronauts fly in rockets and live on the space station.",
    "Cats are very clever animals. They see well in the dark, and their whiskers help them measure space. Kittens love to play and grow up fast.",
    "Robots help people with many jobs. In factories they build cars, and at home they clean the floor. Modern robots can talk and answer questions.",
    "Bees fly from flower to flower and collect honey. Thousands of bees live in one hive, and each has its own job: some gather nectar, some guard the home.",
    "Mountains are tall and beautiful. Snow lies on their peaks, and the air there is clean. Climbers train for a long time to reach the very top.",
    "Water is the source of life. Trees, animals and people cannot live without it. That is why we should save water and keep the tap closed.",
    "Computers are everywhere now: at school, at home, in shops. They count, draw and play music. A person who writes programs is called a developer.",
    "Friendship is the greatest treasure. A true friend helps in hard times and shares your joy. Friends should always be honest with each other.",
    "Football is the most popular sport in the world. Each team has eleven players on the field. A team scores a goal when the ball enters the net.",
    "Books introduce us to new worlds. Reading fairy tales, adventures and science articles is very interesting. People who read a lot know a lot.",
    "In winter snow falls and everything becomes white. Children build snowmen and play snowballs. Some animals sleep until spring: bears, hedgehogs and birds.",
    "The sea holds many secrets. Strange fish live in its deep waters. Dolphins are considered smart and kind, and oceans cover most of our planet.",
    "The internet connects us with any place in the world. Video calls, letters and photos arrive in seconds. But we must use the internet carefully.",
    "In spring trees blossom and birds sing. Fields turn green. Farmers plant seeds, and in autumn they gather the harvest. Every season is beautiful.",
    "Music lifts our mood. Drums, guitars and pianos sound different. Some children love singing, others love dancing. Music is a wonderful art.",
    "Ants are small but very strong. They carry things heavier than themselves. An anthill looks like a complex city with roads, rooms and storage halls.",
    "Planes fly faster than birds. They rise into the sky with powerful engines on their wings. Pilots control the plane and deliver passengers safely.",
    "Sport makes us healthy. Morning exercises are useful every day. Running, swimming and jumping train the body. A healthy body means a healthy mind.",
    "Stars decorate the night sky. The brightest stars have their own names. Astronomers watch the sky through telescopes and discover new stars.",
    "Pumpkin, carrot and potato are useful vegetables. They contain many vitamins. We should eat fruit and vegetables every day to stay strong.",
    "Programmers write programs for computers. A program is a set of clear instructions for the machine. Every program starts with simple commands. You can learn to code too.",
    "The desert is a hot and dry place. Camels and lizards live there. Desert plants know how to save water, and at night the desert is cool and starry.",
    "In autumn birds fly to warm countries. Swallows, cranes and storks travel thousands of kilometres. In spring they return home and build their nests.",
    "At school we learn to read, write and count. Teachers give us knowledge. Working on projects with classmates is fun, and every lesson teaches something new.",
    "Family is our closest people. Parents take care of us, and grandmother tells fairy tales. In a family it is important to help and respect each other.",
    "Rain falls from clouds and waters the earth. After it, a rainbow may appear in the sky. A rainbow has seven colours: red, yellow, green and others.",
    "A bicycle is eco-friendly transport. It needs no petrol and does not pollute the air. Riding a bike strengthens legs and teaches balance.",
    "Dinosaurs lived millions of years ago. Some were huge, some were tiny. We know about them from fossils that scientists show in museums.",
    "Sleep gives the body rest. Children should sleep nine to ten hours at night. Good sleep strengthens memory and improves mood. Do not play on your phone before bed.",
    "Dreams have no limits. Some want to become doctors, some pilots, some programmers. To make a dream come true, study and act. Every big thing starts with a small step."
  ]
};
